### ISSUE TITLE
请问cameras_sphere.npz怎么获取

### ISSUE THREAD

**Issue by zhao-you-fei** [js-duan/texture_map#2]
请问用自己的数据的话那个examples文件夹下的cameras_sphere.npz怎么获取
![image](https://user-images.githubusercontent.com/75787742/221884411-33af0d6e-c084-4cb9-a294-b8accf4090a1.png)
右边这两幅图怎么得出

**Comment by duanfxld** [comment]
你好，我刚更新了一下，可以用[gen_camera.py](https://github.com/js-duan/texture_map/blob/master/gen_camera.py)生成需要的相机文件；增加--label 可以生成右侧两图

**Comment by zhao-you-fei** [comment]
感谢您的回复，等下我就试试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "js-duan/texture_map"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 下午2:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [js-duan/texture_map] 请问cameras_sphere.npz怎么获取 (Issue #2)





 
你好，我刚更新了一下，可以用gen_camera.py生成需要的相机文件；增加--label 可以生成右侧两图
