### ISSUE TITLE
mesh

### ISSUE THREAD

**Issue by hollow857** [js-duan/texture_map#3]
Can I share the script for generating mesh. ply？

**Comment by duanfxld** [comment]
3d reconstruction?

**Comment by hollow857** [comment]
yes，Triangle mesh generation from point cloud reconstruction

**Comment by hollow857** [comment]
> 3d reconstruction?

yes，Triangle mesh generation from point cloud reconstruction

**Comment by duanfxld** [comment]
you can try Poisson surface reconstruction algorithm

**Comment by hollow857** [comment]
> you can try Poisson surface reconstruction algorithm

My point cloud is messy and irregular. Do you have a good way to handle this

**Comment by hollow857** [comment]
Do you have a corresponding paper for the code

**Comment by duanfxld** [comment]
mvs-texturing
